//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayurVrude_25_Nov
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblclassstudent
    {
        public long c_classstudentid { get; set; }
        public Nullable<long> c_classid { get; set; }
        public Nullable<long> c_studentid { get; set; }
    }
}
